# Generated by Django 5.2.4 on 2025-08-02 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('totalEpisode', models.IntegerField()),
                ('totalView', models.IntegerField()),
                ('totalLike', models.IntegerField()),
                ('gname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comicgenre')),
            ],
        ),
    ]
