# Generated by Django 5.2.4 on 2025-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
    ]
