# Generated by Django 5.2.4 on 2025-08-03 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_comicdetails_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EpisodeName', models.CharField(max_length=100)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='comics_chapters/')),
                ('totalEpisode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comicdetails')),
            ],
        ),
    ]
