# Generated by Django 5.2.4 on 2025-08-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_comidepisodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidepisodes',
            name='EpisodeNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
