# Generated by Django 5.2.4 on 2025-08-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_comidepisodes_episodeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicdetails',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='comics_poster/'),
        ),
    ]
