# Generated by Django 5.2.4 on 2025-09-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0005_comicdetails_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicdetails',
            name='comic_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
